apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: diabuoai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: diabuoai/worker:latest
          envFrom:
            - secretRef:
                name: diabuoai-secrets
